hacky fix for #107
crypto-power/cryptopower pull request #113
Opened 2023-09-27 06:03 UTC by CPunch

kind of wanted to give a shot at this, all of the wallet sync code is in wallet_selector_page.go, would it make sense to split it out or would a hacky fix like this be suitable?

2023-09-27 18:33 UTC, crux25 commented
It is better to split the code, move the sync startup logic to home page. Calling wallet selector's navigation function while on home page will potentially introduce bugs in future, devs will assume that `OnNavigatedTo()` and  `OnNavigatedFrom()` are called only when the page is created and destroyed.

2023-09-27 19:59 UTC, Sirmorrison commented on ui/page/root/home_page.go
> +		pg.OnNavigatedFrom()
This is really hacky lol.

The only thought coming to mind is to load the wallets, and have them sync in background pending when we view the loaded wallets on the wallets page.

2023-09-29 16:20 UTC, dreacot commented
@CPunch please fix branch conflicts

2023-09-30 00:13 UTC, ukane-philemon commented on ui/page/root/home_page.go
> +			}()
I don't think there’s a need for the nested goroutine.

2023-09-30 00:25 UTC, ukane-philemon reviewed
Quite straight forward.

2023-09-30 00:25 UTC, ukane-philemon commented on ui/page/root/home_page.go
> +		}
I think this check is inverted.

2023-09-30 00:27 UTC, ukane-philemon commented
Looks good, you can update the title.

2023-10-02 18:30 UTC, ukane-philemon requested changes
Almost.

2023-10-02 22:54 UTC, dreacot commented
@CPunch you have branch conflicts

2023-10-02 23:48 UTC, CPunch commented on ui/page/root/home_page.go
> -	hp.CurrentPage().OnNavigatedTo()
looks like this caused a crash else where. when this line is included, we get a panic at 

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x134e042]

goroutine 45 [running]:
github.com/crypto-power/cryptopower/ui/page/root.(*OverviewPage).listenForMixerNotifications.func1()
        /home/cpunch/projects/cryptopower/ui/page/root/overview_page.go:878 +0x2c2
created by github.com/crypto-power/cryptopower/ui/page/root.(*OverviewPage).listenForMixerNotifications in goroutine 37
        /home/cpunch/projects/cryptopower/ui/page/root/overview_page.go:848 +0x6f8
```

2023-10-02 23:56 UTC, ukane-philemon requested changes
@CPunch, I think this PR is GTG after this.

2023-10-02 23:56 UTC, ukane-philemon commented on ui/page/root/home_page.go
> +		return
Missed this. I think we should fall through (i.e remove the `return`) so we get to try again after the first 10 sec until we successfully start syncing.

2023-10-02 23:59 UTC, ukane-philemon commented on ui/page/root/home_page.go
> +	// Watchonly wallets do not have any password neithers need one.
nit: neithers -> neither

2023-10-03 01:46 UTC, ukane-philemon approved these changes

2023-10-03 02:00 UTC, dreacot approved these changes

2023-10-03 02:01 UTC, merged