Overview mixer card
crypto-power/cryptopower pull request #118
Opened 2023-09-27 13:38 UTC by crux25

This MR adds live data to the mixer card on the overview page.

2023-09-28 00:38 UTC, dreacot requested changes
per the figma design, this is meant to take full width, when mixer isn't running

![Screenshot from 2023-09-27 18-12-27](https://github.com/crypto-power/cryptopower/assets/25265396/e3b4dc2f-4448-4805-8213-5d75e1349246)

the right side of the mixer card has inconsistent padding, the gray area overflows

![Screenshot from 2023-09-27 18-20-18](https://github.com/crypto-power/cryptopower/assets/25265396/a50ab4d3-ac6d-4e8c-9a9e-e9aa69ebde05)

2023-09-28 13:38 UTC, ukane-philemon requested changes
<img width="799" alt="Screenshot 2023-09-28 at 2 33 39 PM" src="https://github.com/crypto-power/cryptopower/assets/57448127/31c486ac-512b-44cd-a56e-692da631b477">

The wallet card does not align with the design(smaller and still takes full width when there's no mixing card) and the top left and bottom left border needs a little attention.

PS: I need help with finding the option to toggle mixing so I can see the view too.

2023-09-28 13:54 UTC, dreacot commented
>PS: I need help with finding the option to toggle mixing so I can see the view too.

@ukane-philemon open a decred wallet, click o stakeshuffle, you can start mixing there(ensure you have funds in your unmixed accoun)

![Screenshot from 2023-09-28 07-53-27](https://github.com/crypto-power/cryptopower/assets/25265396/06891781-f3d4-40ef-bf13-5aeb8746999d)

2023-09-28 14:00 UTC, ukane-philemon requested changes

2023-09-28 14:00 UTC, ukane-philemon commented on ui/page/root/overview_page.go
> +				// Store the slide keys in a slice to maitain a consistence slide sequence.
nit: maitain

2023-09-28 14:07 UTC, dreacot requested changes
Stopping the mixer doesn't update the overview page

step 1: i click the arrow to take me to the mixer page

![Screenshot from 2023-09-28 08-05-09](https://github.com/crypto-power/cryptopower/assets/25265396/7960dbea-22fa-474f-a730-c5a21da7a478)

step 2: i cancel the mixer operation for my wallet (qwerty)

![Screenshot from 2023-09-28 08-06-05](https://github.com/crypto-power/cryptopower/assets/25265396/9fe46952-b15e-4b47-9fb1-ffc32260d500)

step 3: i head back to the overview page, but the mixer card for my wallet (qwerty) is still showing

![Screenshot from 2023-09-28 08-06-33](https://github.com/crypto-power/cryptopower/assets/25265396/5520d304-36b1-4f5d-88ca-0d2e42fc4222)

2023-09-28 14:28 UTC, ukane-philemon commented
RE: https://github.com/crypto-power/cryptopower/pull/118#pullrequestreview-1648898561

I've seen the updated designs. Only the borders need a little touchup.

2023-09-29 09:08 UTC, Sirmorrison commented
I just noticed a regression somewhere in the image layoutSize2() code base that should fix the layout issue @crux25 is having.

Should be  `dst := image.NewRGBA(image.Rectangle{Max: image.Point{X: int(width), Y: int(height * 2)}})`

not `dst := image.NewRGBA(image.Rectangle{Max: image.Point{X: int(width * 2), Y: int(height * 2)}})`

the regression was introduced in this PR https://github.com/crypto-power/cryptopower/pull/95, however from the issue opened i see it fixed a layout bug on linux.

so i will recommend leaving the card layout as it is as it is not from this PR and we can have and issue that will resolve the layout bug.


> <img alt="Screenshot 2023-09-28 at 2 33 39 PM" width="799" src="https://user-images.githubusercontent.com/57448127/271300631-31c486ac-512b-44cd-a56e-692da631b477.png">
> The wallet card does not align with the design(smaller and still takes full width when there's no mixing card) and the top left and bottom left border needs a little attention.
> 
> PS: I need help with finding the option to toggle mixing so I can see the view too.

2023-09-29 14:14 UTC, crux25 commented
> Stopping the mixer doesn't update the overview page
> 
> step 1: i click the arrow to take me to the mixer page
> 
Resolved.

2023-09-29 15:56 UTC, dreacot commented
> so i will recommend leaving the card layout as it is as it is not from this PR and we can have and issue that will resolve the layout bug.

please link an issue when it has been opened

2023-09-29 15:58 UTC, dreacot commented on ui/page/root/overview_page.go
> +		// Append the mixer slide widgets in an ananymouse function. This stops the
```suggestion
		// Append the mixer slide widgets in an anonymous function. This stops the
```

2023-09-29 16:01 UTC, dreacot requested changes

2023-09-29 16:01 UTC, dreacot commented on ui/page/root/overview_page.go
> +				// Store the slide keys in a slice to maintain a consistence slide sequence.
```suggestion
				// Store the slide keys in a slice to maintain a consistent slide sequence.
```

2023-09-29 16:09 UTC, dreacot commented
> Stopping the mixer doesn't update the overview page
> 
> step 1: i click the arrow to take me to the mixer page
> 
> ![Screenshot from 2023-09-28 08-05-09](https://user-images.githubusercontent.com/25265396/271310827-7960dbea-22fa-474f-a730-c5a21da7a478.png)
> 
> step 2: i cancel the mixer operation for my wallet (qwerty)
> 
> ![Screenshot from 2023-09-28 08-06-05](https://user-images.githubusercontent.com/25265396/271311154-9fe46952-b15e-4b47-9fb1-ffc32260d500.png)
> 
> step 3: i head back to the overview page, but the mixer card for my wallet (qwerty) is still showing
> 
> ![Screenshot from 2023-09-28 08-06-33](https://user-images.githubusercontent.com/25265396/271311263-5520d304-36b1-4f5d-88ca-0d2e42fc4222.png)

i repeated this step and got a crash, see the log below

```
panic: assignment to entry in nil map

goroutine 167 [running]:
github.com/crypto-power/cryptopower/ui/page/root.(*OverviewPage).listenForMixerNotifications(0xc003e35b00)
        /home/kennedy/Projects/src/github.com/cryptopower/cryptopower/ui/page/root/overview_page.go:862 +0x4db
github.com/crypto-power/cryptopower/ui/page/root.(*OverviewPage).OnNavigatedTo(0xc003e35b00)
        /home/kennedy/Projects/src/github.com/cryptopower/cryptopower/ui/page/root/overview_page.go:161 +0x168
github.com/crypto-power/cryptopower/app.(*PageStack).Pop(0xc002a8d710)
        /home/kennedy/Projects/src/github.com/cryptopower/cryptopower/app/pagestack.go:93 +0x138
github.com/crypto-power/cryptopower/app.(*MasterPage).CloseCurrentPage(0xc0005de370)
        /home/kennedy/Projects/src/github.com/cryptopower/cryptopower/app/masterpage.go:56 +0x25
github.com/crypto-power/cryptopower/ui/page/root.(*MainPage).HandleUserInteractions(0xc01be27500)
        /home/kennedy/Projects/src/github.com/cryptopower/cryptopower/ui/page/root/main_page.go:416 +0x163
github.com/crypto-power/cryptopower/ui/page/root.(*HomePage).HandleUserInteractions(0xc004027b00)
        /home/kennedy/Projects/src/github.com/cryptopower/cryptopower/ui/page/root/home_page.go:131 +0x67
github.com/crypto-power/cryptopower/ui.(*Window).handleFrameEvent(0xc000191c20, {{0xc13ddb7f3a26a185, 0xe5055fbdd, 0x2e53a40}, {0x3f800000, 0x3f800000}, {0x320, 0x28a}, {0x0, 0x0, ...}, ...})
        /home/kennedy/Projects/src/github.com/cryptopower/cryptopower/ui/window.go:233 +0x14c
github.com/crypto-power/cryptopower/ui.(*Window).HandleEvents(0xc000191c20)
        /home/kennedy/Projects/src/github.com/cryptopower/cryptopower/ui/window.go:206 +0x2b9
main.main.func3()
        /home/kennedy/Projects/src/github.com/cryptopower/cryptopower/main.go:110 +0x1d
created by main.main
        /home/kennedy/Projects/src/github.com/cryptopower/cryptopower/main.go:108 +0x61b
exit status 2
```

2023-09-29 19:37 UTC, dreacot approved these changes

2023-10-02 07:38 UTC, Sirmorrison commented
Associated issue https://github.com/crypto-power/cryptopower/issues/140

2023-10-02 07:40 UTC, Sirmorrison approved these changes

2023-10-02 16:30 UTC, merged