Implement total USD asset balance
crypto-power/cryptopower pull request #131
Opened 2023-09-29 08:57 UTC by Sirmorrison

Fix #77

2023-09-29 10:36 UTC, ukane-philemon commented
Did a little test and noticed:
1. The assets card does not update the dollar val display when the rate source is disabled from the settings page but it does when it's enabled.
2. I think this is the PR that should remove the little toggle at the top as per the discussion on matrix.

2023-09-29 16:31 UTC, dreacot commented
please resolve branch conflicts

2023-09-29 16:43 UTC, dreacot commented
on testing the functionality i noticed there might have been a miscommunication with the way this should work, the total USD Balance, works with the `Fetch Exchange Rate` settings, the toggle might have been confusing

> I think this is the PR that should remove the little toggle at the top as per the discussion on matrix.

@ukane-philemon is right, remove the toggle, if rate fetching is enabled from the settings page, then it's enabled everywhere including the total usd balance, if it's disabled in settings, then it's disabled everywhere

also the text should change to "Total USD value"

![Screenshot from 2023-09-29 10-36-05](https://github.com/crypto-power/cryptopower/assets/25265396/58e0a4a1-f326-43d1-9357-bd412ffc571e)

Also please update the info text to say that this feature can be enabled or disabled from the app settings
![Screenshot from 2023-09-29 10-40-18](https://github.com/crypto-power/cryptopower/assets/25265396/f58e72b9-5d2f-42c5-b1c7-125537360de7)

2023-09-29 16:45 UTC, dreacot requested changes

2023-09-29 16:45 UTC, dreacot commented on ui/cryptomaterial/image.go
> +	dst := image.NewRGBA(image.Rectangle{Max: image.Point{X: int(width), Y: int(height * 2)}})
This reintroduces this issue

![Screenshot from 2023-09-29 10-44-42](https://github.com/crypto-power/cryptopower/assets/25265396/8dbe3a19-d5b6-4639-a175-8d9c9ee1ab1c)

2023-10-02 16:35 UTC, dreacot requested changes
Looks good overall!

hiding my balance doesn't persist when i close and reopen the app

![Screenshot from 2023-10-02 10-34-47](https://github.com/crypto-power/cryptopower/assets/25265396/3d9014b0-7bfe-49ed-93f2-e3b3a294a6e5)

2023-10-02 18:58 UTC, dreacot approved these changes

2023-10-02 19:14 UTC, merged