fix exchange rate bugs
crypto-power/cryptopower pull request #148
Opened 2023-10-04 14:40 UTC by ukane-philemon

Closes #57 

- Return early for `dcr-ltc` market as Binance does not support it yet.
- Fix the bug that caused weird estimated rates.
- Improve the estimated rates display so it's clear.
- Fix comment formatting and typos.

<img width="797" alt="Screenshot 2023-10-04 at 2 39 51 PM" src="https://github.com/crypto-power/cryptopower/assets/57448127/606e7045-ad16-48e6-9125-011427d098cf">
<img width="396" alt="Screenshot 2023-10-04 at 3 15 22 PM" src="https://github.com/crypto-power/cryptopower/assets/57448127/2a494028-260b-4f2c-8dd0-a89deaec8485">
<img width="410" alt="Screenshot 2023-10-04 at 3 21 01 PM" src="https://github.com/crypto-power/cryptopower/assets/57448127/02ec83b7-329f-4681-ab53-2f5766da153c">

Note: `instantswap.ExchangeRateInfo.EstimatedAmount` was previously unused but it gives the correct values for it's current use so I'm using it instead of `instantswap.ExchangeRateInfo.ExchangeRate`.

2023-10-04 17:31 UTC, dreacot commented
binance rate still shows on the order scheduler modal

![Screenshot from 2023-10-04 11-30-23](https://github.com/crypto-power/cryptopower/assets/25265396/c75e9ae9-742e-4c79-a6f4-57cb9afc6251)

2023-10-04 17:39 UTC, dreacot requested changes

2023-10-04 17:39 UTC, dreacot commented on libwallet/ext/service.go
> +		// Return early for dcr-ltc markets ad binance does not support this
```suggestion
		// Return early for dcr-ltc markets as binance does not support this
```

2023-10-04 17:39 UTC, dreacot commented on libwallet/instantswap.go
> +		log.Info(ext.Binance+" rate: 1 %s ~= %f %s", fromCur, binanceRate, toCur)
this can be localized, seems you already have a string entry for it

2023-10-04 18:32 UTC, ukane-philemon commented
> binance rate still shows on the order scheduler modal

Nice catch. I was unable to sync LTC atm and could not test without syncing.

2023-10-05 18:43 UTC, dreacot approved these changes
LGTM!

2023-10-05 18:43 UTC, merged