Add txs and stakes to the overview page
crypto-power/cryptopower pull request #157
Opened 2023-10-06 17:45 UTC by crux25

This MR adds tx and staking data on the overview page. Closes  #84

2023-10-09 21:26 UTC, dreacot commented
the "vote" text and the wallet name seem misaligned

![Screenshot from 2023-10-09 15-24-26](https://github.com/crypto-power/cryptopower/assets/25265396/5c024805-2516-45b2-b3fb-32e5e2a72731)

2023-10-09 21:43 UTC, dreacot commented
mixed funds also seem to be preceded by a negative sign

![Screenshot from 2023-10-09 15-43-02](https://github.com/crypto-power/cryptopower/assets/25265396/5a751b68-78ea-4d77-a380-28ddba9729dd)

2023-10-11 11:25 UTC, Sirmorrison requested changes
First pass

2023-10-11 11:25 UTC, Sirmorrison commented on ui/page/components/components.go
> +						amount := wal.ToAmount(row.Transaction.Amount).String()
```suggestion
```

2023-10-11 11:25 UTC, Sirmorrison commented on ui/page/components/components.go
> +							walBal := wal.ToAmount(row.Transaction.Amount).String()
```suggestion
```

2023-10-11 11:25 UTC, Sirmorrison commented on ui/page/components/components.go
> +							walBalTxt := l.Theme.Label(values.TextSize12, walBal)
```suggestion
							walBalTxt := l.Theme.Label(values.TextSize12, amount)
```

2023-10-11 11:25 UTC, Sirmorrison commented on ui/page/components/components.go
> +							if dcrAsset, ok := wall.(*dcr.Asset); ok {
```suggestion
							if dcrAsset, ok := wal.(*dcr.Asset); ok {
```

2023-10-11 11:25 UTC, Sirmorrison commented on ui/page/components/components.go
> +							if dcrAsset, ok := wall.(*dcr.Asset); ok {
```suggestion
							var ticketSpender *sharedW.Transaction
							if dcrAsset, ok := wal.(*dcr.Asset); ok {
```

2023-10-11 11:25 UTC, Sirmorrison commented on ui/page/components/components.go
> +							assetIcon := CoinImageBySymbol(l, wal.GetAssetType(), wal.IsWatchingOnlyWallet())
```suggestion
```

2023-10-11 11:25 UTC, Sirmorrison commented on ui/page/components/components.go
> +								assetIcon := CoinImageBySymbol(l, wal.GetAssetType(), wal.IsWatchingOnlyWallet())
```suggestion
```

2023-10-11 11:25 UTC, Sirmorrison commented on ui/page/components/components.go
> +							walName := l.Theme.Label(values.TextSize12, wal.GetWalletName())
```suggestion
```

2023-10-11 11:25 UTC, Sirmorrison commented on ui/page/components/components.go
> +								walName := l.Theme.Label(values.TextSize12, wal.GetWalletName())
```suggestion
```

2023-10-11 11:25 UTC, Sirmorrison commented on ui/page/components/components.go
> +					//layout.Rigid(status.Layout),
remove

2023-10-11 11:25 UTC, Sirmorrison commented on ui/page/components/components.go
> +						}),
```suggestion
						layout.Rigid(l.Theme.Label(values.TextSize18, txStatus.Title).Layout),
```

2023-10-11 11:30 UTC, Sirmorrison requested changes

2023-10-11 11:30 UTC, Sirmorrison commented on ui/page/components/components.go
> +	txStatus := TransactionTitleIcon(l, wal, &row.Transaction)
```suggestion
	wal := l.WL.AssetsManager.WalletWithID(row.Transaction.WalletID)
	amount := wal.ToAmount(row.Transaction.Amount).String()
	assetIcon := CoinImageBySymbol(l, wal.GetAssetType(), wal.IsWatchingOnlyWallet())
	walName := l.Theme.Label(values.TextSize12, wal.GetWalletName())
	txStatus := TransactionTitleIcon(l, wal, &row.Transaction)
```

2023-10-11 11:30 UTC, itswisdomagain commented on ui/page/components/components.go
> +func LayoutTransactionRow2(gtx layout.Context, l *load.Load, row TransactionRow) layout.Dimensions {
Do both actually. Rename and update the comment.

2023-10-16 17:19 UTC, dreacot commented
staking activities only show one item for me, when i have hundreds of staking activity

the decred logo and wallet name is still not aligned on mixed and staking transactions

![Screenshot from 2023-10-16 11-18-08](https://github.com/crypto-power/cryptopower/assets/25265396/fe917f39-f666-4a5a-9140-fed664d84b7b)

2023-10-17 08:03 UTC, Sirmorrison requested changes

2023-10-17 08:03 UTC, Sirmorrison commented on ui/page/components/components.go
> +			reqConf := l.WL.AssetsManager.WalletWithID(row.Transaction.WalletID).RequiredConfirmations()
```suggestion
			reqConf :=wal.RequiredConfirmations()
```

2023-10-17 12:40 UTC, crux25 commented
> staking activities only show one item for me, when i have hundreds of staking activity
> 
> the decred logo and wallet name is still not aligned on mixed and staking transactions
> 
> ![Screenshot from 2023-10-16 11-18-08](https://user-images.githubusercontent.com/25265396/275596188-fe917f39-f666-4a5a-9140-fed664d84b7b.png)

The staking activities, does it say "Vote"?

2023-10-17 12:53 UTC, crux25 commented on ui/page/components/components.go
> +func LayoutTransactionRow2(gtx layout.Context, l *load.Load, row TransactionRow) layout.Dimensions {
I removed the method entirely. Better to have LayoutTransactionRow draw both forms of tx layout.

2023-10-19 17:29 UTC, dreacot commented
> > staking activities only show one item for me, when i have hundreds of staking activity
> > the decred logo and wallet name is still not aligned on mixed and staking transactions
> > ![Screenshot from 2023-10-16 11-18-08](https://user-images.githubusercontent.com/25265396/275596188-fe917f39-f666-4a5a-9140-fed664d84b7b.png)
> 
> The staking activities, does it say "Vote"?

i'm not sure what you mean?

this is my staking list

![Screenshot from 2023-10-19 11-28-40](https://github.com/crypto-power/cryptopower/assets/25265396/775c1867-6c59-4d69-8cfc-47faecc448e5)

this is what i see on overview page
![Screenshot from 2023-10-19 11-27-37](https://github.com/crypto-power/cryptopower/assets/25265396/2f3cfae1-9f05-4118-8cf7-deb4698e3d42)

2023-10-24 17:18 UTC, JustinBeBoy requested changes

2023-10-24 17:18 UTC, JustinBeBoy commented on ui/page/root/overview_page.go
> +											return layout.Dimensions{}
```suggestion
											return D{}
```

We can agree to use D{} instead of layout.Dimensions{}

2023-10-24 17:18 UTC, JustinBeBoy commented on ui/page/root/overview_page.go
> +										return layout.Dimensions{}
```suggestion
										return D{}
```

We can agree to use D{} instead of layout.Dimensions{}

2023-10-24 17:19 UTC, dreacot approved these changes

2023-10-24 17:21 UTC, JustinBeBoy approved these changes

2023-10-24 17:38 UTC, Sirmorrison requested changes
After these minor changes the PR looks good to go.

2023-10-24 17:38 UTC, Sirmorrison commented on ui/page/components/components.go
> +							return walBalTxt.Layout(gtx)
```suggestion
                                                        if isTxPage {
								return D{}
							}
							if row.Transaction.Type == txhelper.TxTypeMixed {
								return cryptomaterial.LinearLayout{
									Width:       cryptomaterial.WrapContent,
									Height:      cryptomaterial.WrapContent,
									Orientation: layout.Horizontal,
									Direction:   layout.W,
									Alignment:   layout.Middle,
								}.Layout(gtx,
									layout.Rigid(func(gtx C) D {
										// mix denomination
										mixedDenom := wal.ToAmount(row.Transaction.MixDenomination).String()
										txt := l.Theme.Label(values.TextSize12, mixedDenom)
										txt.Color = l.Theme.Color.GrayText2
										return txt.Layout(gtx)
									}),
									layout.Rigid(func(gtx C) D {
										// Mixed outputs count
										if row.Transaction.MixCount > 1 {
											label := l.Theme.Label(values.TextSize12, fmt.Sprintf("x%d", row.Transaction.MixCount))
											label.Color = l.Theme.Color.GrayText2
											return layout.Inset{Left: values.MarginPadding4}.Layout(gtx, label.Layout)
										}
										return D{}
									}),
								)
							}

							walBalTxt := l.Theme.Label(values.TextSize12, amount)
							walBalTxt.Color = l.Theme.Color.GrayText2
							return walBalTxt.Layout(gtx)
```
return early. If `isTxPage`  no need checking or comparing tx type

2023-10-24 17:38 UTC, Sirmorrison commented on ui/page/components/components.go
> +							return layout.Inset{Left: values.MarginPadding4}.Layout(gtx, lbl.Layout)
```suggestion
							txt :=fmt.Sprintf("%.2f", amnt)
							if amnt > 0 {
								txt = fmt.Sprintf("+%.2f", amnt)
							}
							return layout.Inset{Left: values.MarginPadding4}.Layout(gtx,  l.Theme.Label(values.TextSize12, txt).Layout)
```

2023-10-24 17:38 UTC, Sirmorrison commented on ui/page/components/components.go
> +										return lbl.Layout(gtx)
```suggestion
										return l.Theme.Label(values.TextSize12, durationTxt).Layout(gtx)
```

2023-10-24 17:38 UTC, Sirmorrison commented on ui/page/root/overview_page.go
> +								return pg.Theme.Body1(values.StrNoStaking).Layout(gtx)
remove space

2023-10-24 23:35 UTC, dreacot approved these changes

2023-10-24 23:35 UTC, merged