add onboarding screens
crypto-power/cryptopower pull request #189
Opened 2023-10-16 09:31 UTC by Sirmorrison

Fix #144 

This Pr introduces new onboarding pages.
<img width="800" alt="image" src="https://github.com/crypto-power/cryptopower/assets/27733432/3552db8b-321c-4ebd-9a5b-ca470cba7d65">

2023-10-16 17:30 UTC, dreacot commented
after going through the onboarding steps i get to this screen below

![Screenshot from 2023-10-16 11-27-17](https://github.com/crypto-power/cryptopower/assets/25265396/5ae54e6d-4ae0-4820-8fbb-453b27cbe290)

i add a wallet, and on quiting the app and reopening i'm taken to the on boarding screens again, even after completing the onboarding screens again, i'm taken to to the add wallet screen even though i already have a wallet

2023-10-17 05:16 UTC, Sirmorrison commented
> after going through the onboarding steps i get to this screen below
> 
> ![Screenshot from 2023-10-16 11-27-17](https://user-images.githubusercontent.com/25265396/275598224-5ae54e6d-4ae0-4820-8fbb-453b27cbe290.png)
> 
> i add a wallet, and on quiting the app and reopening i'm taken to the on boarding screens again, even after completing the onboarding screens again, i'm taken to to the add wallet screen even though i already have a wallet

yes.. that seems to be the flow of the design created and when i asked, @itswisdomagain said this should be the flow. the design has a button for skipping to the home page by clicking the skip wallet creation button.

2023-10-17 05:17 UTC, Sirmorrison commented
You originally cannot skip wallet creation if you dont have a wallet already.

2023-10-17 16:08 UTC, dreacot commented
> You originally cannot skip wallet creation if you dont have a wallet already.

also skipping wallet creating wasn't part of the original issue, the original issue regarding skipping wallet creation has been closed https://github.com/crypto-power/cryptopower/issues/143

2023-10-17 16:10 UTC, dreacot commented
> i add a wallet, and on quiting the app and reopening i'm taken to the on boarding screens again, even after completing the onboarding screens again, i'm taken to to the add wallet screen even though i already have a wallet

from my original comment, the issue i''m outlining is that the onboarding screens always show up with each start of the app. that should not be the case, then the user has created a wallet the onboarding screens should not show up anymore

2023-10-17 20:52 UTC, dreacot commented on ui/cryptomaterial/icon_gallery.go
> +	i.MiltiWalletIcon = NewImage(decredIcons["miltiWalletIcon"])
did you mean this to say multiwallet icon?

2023-10-18 05:26 UTC, Sirmorrison commented
> > You originally cannot skip wallet creation if you dont have a wallet already.
> 
> also skipping wallet creating wasn't part of the original issue, the original issue regarding skipping wallet creation has been closed #143

I didnt implement skipping wallet creation. Its just a button on the screens.

2023-10-18 16:11 UTC, dreacot commented
okay there seems to be some miscommunication so i'd try and clarify

i just built the latest commit on this PR and here are my observations;

- the on boarding pages now work as intended (i.e not showing when there's already a created wallet)

there are still some things to fix;

1. there should be a skip button under the next button, and if the user clicks the skip button, it takes them to the final screen of the onboarding page as seen below

![Screenshot from 2023-10-18 10-09-27](https://github.com/crypto-power/cryptopower/assets/25265396/1fb5bffe-e279-45bb-98ef-529333824067)

2. while discussing with @itswisdomagain we decided to not show the skip wallet creation button as there's not much a user can do without a wallet (asides viewing market rate and proposals) . see this comment https://github.com/crypto-power/cryptopower/issues/143#issuecomment-1762327762

2023-10-18 16:22 UTC, dreacot requested changes

2023-10-18 16:22 UTC, dreacot commented on ui/page/start_page.go
> +	onBoardingScreenTitle string
```suggestion
	Title string
```

just title is sufficient

`onBoardingScreen.Title`

2023-10-18 16:58 UTC, dreacot commented
> > okay there seems to be some miscommunication so i'd try and clarify
> > i just built the latest commit on this PR and here are my observations;
> > 
> > * the on boarding pages now work as intended (i.e not showing when there's already a created wallet)
> > 
> > there are still some things to fix;
> > 
> > 1. there should be a skip button under the next button, and if the user clicks the skip button, it takes them to the final screen of the onboarding page as seen below, the original image attached to this PR is correct
> > 
> > ![Screenshot from 2023-10-18 10-09-27](https://user-images.githubusercontent.com/25265396/276322358-1fb5bffe-e279-45bb-98ef-529333824067.png)
> > 
> > 2. while discussing with @itswisdomagain we decided to not show the skip wallet creation button as there's not much a user can do without a wallet (asides viewing market rate and proposals) . see this comment [allow users skip wallet creation process #143 (comment)](https://github.com/crypto-power/cryptopower/issues/143#issuecomment-1762327762)
> 
> So to address the first point, on element we had a discussion some time back (i will try to reference it), where @itswisdomagain mentioned that the onboarding screens should always show up and we should prevent skipping it, until the user fully onboards.
> 
> If this is the case, the initial skip button wont be needed because the moment the user onboards, these pages are no longer displayed. Add a skip button offers the first user the ability to skip and not view the informations on the pages. This is why the skip button was removed but it can always be added back.

Yes you are correct, skipping it in that case meant not showing the onboarding screens again.

a use could have gone through the 3 onboarding steps and never actually create a wallet, in that case they are already familiar with it, so they can have the skip button to go straight to where they can add a wallet.

so yes, let's add the skip button back

2023-10-19 17:06 UTC, dreacot approved these changes

2023-10-19 17:09 UTC, merged