Add  DEX  support for Cryptopower DCR wallets
crypto-power/cryptopower pull request #269
Opened 2023-11-27 15:31 UTC by ukane-philemon

This MR adds DEX support for cyptopower dcr wallets. An edge case I'm yet to handle is handling wallet removal when it is used by the DEX core. Closes #245.

- Bond payments ✅ 
- Trade: coming soon.

Builds on top of #238.

2023-12-06 00:57 UTC, dreacot commented
@itswisdomagain please take a look

2023-12-08 07:49 UTC, JoeGruffins approved these changes
I'm able to set up a private server to test.

The first time I tried to post bond I saw this but it worked the second try:
![image](https://github.com/crypto-power/cryptopower/assets/34998433/72dbcfab-7221-4827-9fab-5bfe5a1ca1e7)

If I leave the page while waiting on the bonds it forgot my custom server location and certificate. And now I can only see:
![image](https://github.com/crypto-power/cryptopower/assets/34998433/2daff269-9b3e-4175-a138-a5d715b6c70b)


But I guess that's just where the development is at this point?

From the dex server, so I guess all went well.
```
2023-12-08 16:47:44.482 [DBG] AUTH: Activating new bond 4e6fc99f9f375516c1245e0da30096d45dfc01bbf56690384226fe73955e7c47:0 (dcr) committing 10000000 for user d1cf48bbfab73575be3214dfae02de6a9ccf35cee9d64eb8f046a904d01dbb25
2023-12-08 16:47:44.482 [INF] AUTH: Creating new user account d1cf48bbfab73575be3214dfae02de6a9ccf35cee9d64eb8f046a904d01dbb25 from 127.0.0.1, posted first bond in 4e6fc99f9f375516c1245e0da30096d45dfc01bbf56690384226fe73955e7c47:0 (dcr)
2023-12-08 16:47:44.488 [INF] AUTH: Bond accepted: acct d1cf48bbfab73575be3214dfae02de6a9ccf35cee9d64eb8f046a904d01dbb25 from 127.0.0.1 locked 10000000 in 4e6fc99f9f375516c1245e0da30096d45dfc01bbf56690384226fe73955e7c47:0. Bond total 2, tier 2
2023-12-08 16:47:44.497 [DBG] AUTH: User d1cf48bbfab73575be3214dfae02de6a9ccf35cee9d64eb8f046a904d01dbb25 score = 0:0 (0 successes) - 0 (violations) - 0 (0 preimage misses) 
2023-12-08 16:47:44.498 [INF] AUTH: Authenticated account d1cf48bbfab73575be3214dfae02de6a9ccf35cee9d64eb8f046a904d01dbb25 from 127.0.0.1 with 0 active orders, 0 active matches, tier = 2, bond tier = 2, score = 0
```

2023-12-08 09:35 UTC, itswisdomagain commented on libwallet/assets/dcr/dex_asset.go
> +	return cfg.Type != walletTypeSPV, nil
No need to implement the `LiveReconfigurer` interface.

2023-12-08 11:20 UTC, ukane-philemon commented on dexc/core.go
> +	if err != nil && !strings.Contains(err.Error(), "already support" /* this is part of the error string returned if we've already registered a customer wallet */) {
Yes.

2023-12-08 11:21 UTC, ukane-philemon commented
Thanks for the review @JoeGruffins. I’ll get to them.

2023-12-08 12:00 UTC, JustinBeBoy commented
Seems like everything I commented in  #238 , it's hard to tell the changes in PR compared to PR238, I'll come back when PR238 is merged

2023-12-13 02:41 UTC, ukane-philemon commented on libwallet/assets/dcr/dex_asset.go
> +	return cfg.Type != walletTypeSPV, nil
> No need to implement the `LiveReconfigurer` interface.

It's required by `dexdcr.Wallet` interface.

2023-12-13 03:31 UTC, ukane-philemon commented
@JoeGruffins, your comments have been resolved. Please check to confirm.

Note to reviewers: The add server page does not remember custom server details if the user leaves without posting bonds.

2023-12-13 10:36 UTC, JoeGruffins commented
Still seeing that not logged in popup with a fresh cryptopower and then it works the second time.

2023-12-13 13:33 UTC, ukane-philemon commented
> Still seeing that not logged in popup with a fresh cryptopower and then it works the second time.

Huh 🤔.

2023-12-13 15:45 UTC, itswisdomagain submitted a review, later dismissed
Will review again after these.

2023-12-13 15:45 UTC, itswisdomagain commented on libwallet/assets/dcr/dex_asset.go
> +		return false, utils.TranslateError(err)
Upstream doesn't return an error for not exist:
```
if errors.Is(err, walleterrors.NotExist) {
	return false, nil
}
```

2023-12-13 15:45 UTC, itswisdomagain commented on libwallet/assets/dcr/dex_asset.go
> +	bal, err := da.asset.GetAccountBalance(int32(da.dexAccountNumber), &confirms)
I see why `asset.GetAccountBalance` was modified to accept confs now. Please use the internal wallet method for getting account balance. And use the provided ctx as well.

2023-12-13 15:45 UTC, itswisdomagain commented on libwallet/assets/dcr/dex_asset.go
> +}
When mixing is enabled, multiple accounts may be in use. Always use the acctName parameter passed to methods.

2023-12-13 15:45 UTC, itswisdomagain commented on libwallet/assets/dcr/dex_asset.go
> +	asset *Asset
Change this to `wallet *wallet.Wallet`. Use direct methods of the upstream dcrwallet object. That should make this file look more closely like the upstream dex spv file.

2023-12-13 17:37 UTC, dreacot requested changes
after posting bonds, i'm pretty sure i was shown to pay  fee of 0.2 dcr, but i only got debited 0.1 dcr

also i believe a minimum of 1 confirmation is required before you can proceed, but on leaving the trade page and returning to it, i get taken to the market page, i shouldn't go past the bond page until my payment is confirmed
![Screenshot from 2023-12-13 10-33-04](https://github.com/crypto-power/cryptopower/assets/25265396/ead74647-21a5-4a02-a1d7-d7a71c9b6830)

![Screenshot from 2023-12-13 10-33-25](https://github.com/crypto-power/cryptopower/assets/25265396/dc76d5e7-f26d-41b2-b086-554022f244a2)

why does this keep showing every time i go to the dex page
![Screenshot from 2023-12-13 10-33-18](https://github.com/crypto-power/cryptopower/assets/25265396/b7a731fd-c4b5-4d73-8ef9-826c46dae1a7)

2023-12-13 23:51 UTC, ukane-philemon commented
> also i believe a minimum of 1 confirmation is required before you can proceed, but on leaving the trade page and returning to it, i get taken to the market page, i shouldn't go past the bond page until my payment is confirmed

Yes, but once an exchange has been added to core I don't think we need to cache the bond data somewhere just to make the user wait on the bond confirmation page. At this point the bond payment has already been made.

2023-12-14 05:56 UTC, ukane-philemon commented
> i'm pretty sure i was shown to pay fee of 0.2 dcr

Yes, I was previously accounting for bond maintenance.

2023-12-14 06:55 UTC, JoeGruffins commented
I see insufficient balance now. The testnet server also seems to be up now.


https://github.com/crypto-power/cryptopower/assets/34998433/d8243057-9ba5-4039-9cc5-2e78df48e045

2023-12-14 07:15 UTC, ukane-philemon commented
> I see insufficient balance now.

Hmm, I've tested several times (with block wait times over 13min)  yet I didn't see this. I'm still looking and will suggest some changes.

2023-12-14 08:10 UTC, ukane-philemon commented
> > I see insufficient balance now.
> 
> Hmm, I've tested several times (with block wait times over 13min) yet I didn't see this. I'm still looking and will suggest some changes.

@JoeGruffins, this was caused by a "nasty bug". `v0.6.3/client/asset/dcr/config.go#L33` required specifying a primary account which has been removed from dex master (for spv wallets only). Fixed by [3c7246f](https://github.com/crypto-power/cryptopower/pull/269/commits/3c7246f58cb9f2c112252e0a7daa31dde3e7c3e0).

2023-12-14 17:51 UTC, dreacot approved these changes
Tested ACK

2023-12-14 17:59 UTC, ukane-philemon commented
@JoeGruffins, please can you confirm the error has been fixed on your end?

2023-12-15 04:02 UTC, JoeGruffins approved these changes
No problems now!

2023-12-18 13:45 UTC, JustinBeBoy approved these changes

2023-12-18 19:54 UTC, merged