Send page layout update.
crypto-power/cryptopower pull request #310
Opened 2023-12-06 09:56 UTC by Sirmorrison

Fix #215

2023-12-14 16:10 UTC, JustinBeBoy requested changes
1. Seem like you update segmented affected other page

![image](https://github.com/crypto-power/cryptopower/assets/19331824/c8f5ff0c-ff28-4bd5-b410-f7e5ec2253ee)

2. if Fee rate support only BTC I think you can hidden this part
![image](https://github.com/crypto-power/cryptopower/assets/19331824/a068b9af-da51-4493-a782-b95a76a82954)


1 bold text, 2 "Destination Account", 3,4 the gap is too large
![image](https://github.com/crypto-power/cryptopower/assets/19331824/0c59e83e-3dfa-4d67-9182-9b989df8d70e)


I can't select the account has DCR
![image](https://github.com/crypto-power/cryptopower/assets/19331824/584703c6-4313-4d73-a9ef-2ed12703a428)


when typing amount, the address text box autofocus
https://github.com/crypto-power/cryptopower/assets/19331824/30b347a0-828b-4b22-91d3-cc17309d07b5

"add recipient" button not work
![image](https://github.com/crypto-power/cryptopower/assets/19331824/5b070a58-144c-4684-900f-dc26126b5c4c)

2023-12-14 18:08 UTC, dreacot commented on ui/page/components/fee_rate_selector.go
> +					if !fs.isFeerateAPIApproved() || fs.selectedWalletType() == libutils.LTCWalletAsset || fs.selectedWalletType() == libutils.DCRWalletAsset {
btc and ltc, it should not sow in the UI for dcr

2023-12-14 18:11 UTC, dreacot commented
> "add recipient" button not work

@Sirmorrison even though we are not adding the functionality via this PR, the UI should work

2023-12-15 12:20 UTC, Sirmorrison commented on ui/page/components/fee_rate_selector.go
> +					return layout.Flex{Axis: layout.Horizontal}.Layout(gtx,
yes we do for this particular use case.

2023-12-15 12:21 UTC, Sirmorrison commented
`I can't select the account has DCR`
Kindly confirm this is not the current behavior on master reason is i know you are not allowed to send funds directly to a mixed account.

2023-12-15 12:25 UTC, Sirmorrison commented
> > "add recipient" button not work
> 
> @Sirmorrison even though we are not adding the functionality via this PR, the UI should work

A follow up PR will implement this functionality.. in the mean time, i will just hide this button to prevent any confusion.

2023-12-16 09:28 UTC, JustinBeBoy submitted a review, later dismissed
1. it still unresolved
![b1](https://github.com/crypto-power/cryptopower/assets/19331824/474b4c21-8124-49ac-91f9-b739156b847b)

2 Please update `coin selection` layout
![b2](https://github.com/crypto-power/cryptopower/assets/19331824/06b0cd3f-67be-4238-8f7d-8a29116a42b8)

3. dropdown on fee rates need update
![b3](https://github.com/crypto-power/cryptopower/assets/19331824/5b646432-af52-481f-a919-e5c4180d64df)

2023-12-16 09:28 UTC, JustinBeBoy commented on ui/page/components/fee_rate_selector.go
> +					return layout.Flex{Axis: layout.Horizontal}.Layout(gtx,
it causes confusion, you can try the following code

```
gtx.Constraints.Min.X = gtx.Constraints.Max.X
return layout.Inset{Top: values.MarginPadding4}.Layout(gtx, func(gtx C) D {
	return layout.E.Layout(gtx, lbl.Layout)
})
```

2023-12-18 08:35 UTC, Sirmorrison commented
<img width="941" alt="image" src="https://github.com/crypto-power/cryptopower/assets/27733432/2b801147-f3a0-4775-9d65-fa7e51f3f43d">

There are two different designs.. one has `destination amount` and amount has `Amount`.. i am using `Amount` because `Destination Amount` does not make a sense. There is no field titled `Source Amount` so i dont see why we are have `Destination AMount`

2023-12-18 08:36 UTC, Sirmorrison commented
![image](https://github.com/crypto-power/cryptopower/assets/27733432/cf513797-8164-4e44-841c-b7a9fffb66c4)

I dont think resolving issues with the dropdown is ideal in the PR.. for starters its already large enough.. any other UI updated that does not affect functionality will be addressed ina. follow up PR.

2023-12-18 10:22 UTC, JustinBeBoy commented
> <img alt="image" width="941" src="https://private-user-images.githubusercontent.com/27733432/291199372-2b801147-f3a0-4775-9d65-fa7e51f3f43d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI4OTQ3NjAsIm5iZiI6MTcwMjg5NDQ2MCwicGF0aCI6Ii8yNzczMzQzMi8yOTExOTkzNzItMmI4MDExNDctZjNhMC00Nzc1LTlkNjUtZmE3ZTUxZjNmNDNkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE4VDEwMTQyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRmNjJmYmUzNjc4N2I3Yzc3YWRlZjAxNGI1YzlkMWUyMzI4M2EyN2Q4MDFhYWY1OWU4YWRiYzY5NzkyNzgxMmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.mcK2MNQ6iLnF3ro_A4DugpgJe098h5Y0MYXSu2kk1_8">
> There are two different designs.. one has `destination amount` and the other has `Amount`.. i am using `Amount` because `Destination Amount` does not make a sense. There is no field titled `Source Amount` so i dont see why we are have `Destination AMount`

It seems you have made a mistake here, please carefully check the photo I sent, there is only 1 design, not 2, the layout I am talking about here is sent to "wallet", not "address" and you are comparing these two with each other

2023-12-18 10:53 UTC, JustinBeBoy commented
> ![image](https://private-user-images.githubusercontent.com/27733432/291202105-cf513797-8164-4e44-841c-b7a9fffb66c4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI4OTQ3NjAsIm5iZiI6MTcwMjg5NDQ2MCwicGF0aCI6Ii8yNzczMzQzMi8yOTEyMDIxMDUtY2Y1MTM3OTctODE2NC00ZTQ0LTg0MWMtYjdhOWZmZmI2NmM0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE4VDEwMTQyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg2OWUyMWJhZmEzY2NjMGY2NzIxNzE0MjA0Yjk1MzE4MTZkZDM2ZjU1ZGNlNTZhMDg4Y2EyMWI1ZGY2ZTI1NzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.TBKfRK9rrjD5YqbHjiOBBzhgQ9AwVKbg8uWRClMWQ_s)
> 
> I dont think resolving issues with the dropdown is ideal in the PR.. for starters its already large enough.. any other UI updated that does not affect functionality will be addressed ina. follow up PR.

I don't think it's too difficult, dropdown is available now, simply fix the way it displays and it's in this PR, I think
@dreacot  what do you think ?

2023-12-18 19:57 UTC, dreacot commented
> > ![image](https://private-user-images.githubusercontent.com/27733432/291202105-cf513797-8164-4e44-841c-b7a9fffb66c4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI4OTQ3NjAsIm5iZiI6MTcwMjg5NDQ2MCwicGF0aCI6Ii8yNzczMzQzMi8yOTEyMDIxMDUtY2Y1MTM3OTctODE2NC00ZTQ0LTg0MWMtYjdhOWZmZmI2NmM0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE4VDEwMTQyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg2OWUyMWJhZmEzY2NjMGY2NzIxNzE0MjA0Yjk1MzE4MTZkZDM2ZjU1ZGNlNTZhMDg4Y2EyMWI1ZGY2ZTI1NzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.TBKfRK9rrjD5YqbHjiOBBzhgQ9AwVKbg8uWRClMWQ_s)
> > I dont think resolving issues with the dropdown is ideal in the PR.. for starters its already large enough.. any other UI updated that does not affect functionality will be addressed ina. follow up PR.
> 
> I don't think it's too difficult, dropdown is available now, simply fix the way it displays and it's in this PR, I think @dreacot what do you think ?

i see no reason why it should not be resolved here, there a drodowns in master that work as intended already

2023-12-18 21:22 UTC, dreacot commented
i believe this part should be sticky

![Screenshot from 2023-12-18 14-22-32](https://github.com/crypto-power/cryptopower/assets/25265396/4d963d23-b678-46a4-9e12-24b5e48eabc1)

2023-12-19 05:54 UTC, dreacot approved these changes

2023-12-19 05:54 UTC, merged