Update layout for mixer and slider on overview page
crypto-power/cryptopower pull request #316
Opened 2023-12-09 04:50 UTC by JustinBeBoy

Resolve #288 

![image](https://github.com/crypto-power/cryptopower/assets/19331824/b04075ee-9b24-4102-9277-3536cabd6a1c)

2023-12-11 16:45 UTC, dreacot commented
the icon sizes should be smaller on mobile

2023-12-11 16:46 UTC, dreacot requested changes

2023-12-11 16:46 UTC, dreacot commented on ui/window.go
> +	appMinSize := giouiApp.MinSize(values.AppHeight, values.AppHeight)
revert this

2023-12-12 09:07 UTC, JustinBeBoy commented
> the icon sizes should be smaller on mobile

done

2023-12-13 00:40 UTC, dreacot approved these changes

2023-12-13 00:42 UTC, merged