Update proposal card with lastest design
crypto-power/cryptopower pull request #331
Opened 2023-12-14 22:55 UTC by ukane-philemon

- Update proposal card with lastest design (Mobile&Desktop)
- And fix bug where recent proposals are displayed when governance API is off.

Figma(i think the pre-status layout for the desktop looks incomplete on the Figma design as it's not properly aligned):
<img width="381" alt="Screenshot 2023-12-14 at 11 50 11 PM" src="https://github.com/crypto-power/cryptopower/assets/57448127/a6d974ef-4def-4fde-b7d2-812db86a2850">
<img width="815" alt="Screenshot 2023-12-14 at 11 50 41 PM" src="https://github.com/crypto-power/cryptopower/assets/57448127/d648bbab-c761-487e-abe6-2a794da2f478">

This PR:
<img width="373" alt="Screenshot 2023-12-14 at 11 51 35 PM" src="https://github.com/crypto-power/cryptopower/assets/57448127/e223dd5d-a7ac-4d79-96c6-0cc96acc8a77">
<img width="818" alt="Screenshot 2023-12-14 at 11 51 45 PM" src="https://github.com/crypto-power/cryptopower/assets/57448127/0540c341-c8c7-44f2-a33c-3e9c1c2c2a92">

2023-12-15 15:07 UTC, JustinBeBoy commented
seem like this PR effected to proposal page on governance page, please check it

![image](https://github.com/crypto-power/cryptopower/assets/19331824/9f9e2ec1-d94a-4358-b632-0f636c600c73)

2023-12-15 15:08 UTC, JustinBeBoy requested changes
seem like this PR effected to proposal page on governance page, please check it

![image](https://github.com/crypto-power/cryptopower/assets/19331824/9f9e2ec1-d94a-4358-b632-0f636c600c73)

2023-12-18 14:11 UTC, ukane-philemon commented
> seem like this PR effected to proposal page on governance page, please check it

Yh, we use a single component for proposal listing. I need to clarify if the designs I saw on Figma are cleared for implementation.

2023-12-18 21:22 UTC, dreacot commented
> > seem like this PR effected to proposal page on governance page, please check it
> 
> Yh, we use a single component for proposal listing. I need to clarify if the designs I saw on Figma are cleared for implementation.

what was in the app already looked like it worked previously, so i don't see the need to update, we should probably only be updating designs that don't work atm

2023-12-19 08:23 UTC, dreacot commented
not solving as recent proposals looks good already

2023-12-19 08:23 UTC, closed without merging