Add wallet sync info into Overview page
crypto-power/cryptopower pull request #397
Opened 2024-01-15 05:27 UTC by JustinBeBoy

Resolve #376 

**Screenshot**

![image](https://github.com/crypto-power/cryptopower/assets/19331824/bec429f6-ac37-4003-aa88-8bb76d4a2243)

2024-01-16 05:20 UTC, dreacot commented
the bottom controls are not well positioned

<img width="760" alt="Screenshot 2024-01-16 at 6 20 14 AM" src="https://github.com/crypto-power/cryptopower/assets/25265396/83d8877d-34fc-42f6-86f3-9de12d1343ae">

2024-01-16 09:09 UTC, dreacot commented
when a new wallet is create also enable auto sync

2024-01-17 04:10 UTC, dreacot commented
When the backup now button is visible, it affects the positioning of the controls

<img width="743" alt="Screenshot 2024-01-17 at 5 08 57 AM" src="https://github.com/crypto-power/cryptopower/assets/25265396/2431bda9-730b-4050-a277-33bff9fc1292">

clicking on the controls open the wallet info page rather than actually doing the intended job of the controls which is switching the slider
<img width="740" alt="Screenshot 2024-01-17 at 5 09 47 AM" src="https://github.com/crypto-power/cryptopower/assets/25265396/dc15d085-088a-4f4d-a58f-6b8f4eb5c28f">

2024-01-17 04:13 UTC, dreacot commented on ui/page/root/overview_page.go
> +		// }
remove commented code

2024-01-17 04:14 UTC, dreacot requested changes

2024-01-17 04:14 UTC, dreacot commented on ui/page/root/overview_page.go
> +		fmt.Println("----------------------------->")
remove commented code and debug code

2024-01-17 13:46 UTC, JustinBeBoy commented
> 1. When the backup now button is visible, it affects the positioning of the controls
> 2. Clicking backup now from the sync card doesn't show the correct page after trying to leave the wallet info page, clicking the back button on the wallet info page shows the backup checklist
> 
> <img alt="Screenshot 2024-01-17 at 5 08 57 AM" width="743" src="https://private-user-images.githubusercontent.com/25265396/297257242-2431bda9-730b-4050-a277-33bff9fc1292.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU0OTk0NTAsIm5iZiI6MTcwNTQ5OTE1MCwicGF0aCI6Ii8yNTI2NTM5Ni8yOTcyNTcyNDItMjQzMWJkYTktNzMwYi00MDUwLWEyNzctMzNiZmY5ZmMxMjkyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE3VDEzNDU1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMwMjI4NmQ0NTFkODllMDBjMWVhNWQ3MzQ5MTVlZDJkNjBlN2I3NjY3MDc2NDQyOTg3MjQzYzhjOTRjNWRhMGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.7sOz4J-iecg0NIEk4wZB-Kpgxcka5j1RonD0lxRkZ_c">
> clicking on the controls open the wallet info page rather than actually doing the intended job of the controls which is switching the slider <img alt="Screenshot 2024-01-17 at 5 09 47 AM" width="740" src="https://private-user-images.githubusercontent.com/25265396/297257345-dc15d085-088a-4f4d-a58f-6b8f4eb5c28f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU0OTk0NTAsIm5iZiI6MTcwNTQ5OTE1MCwicGF0aCI6Ii8yNTI2NTM5Ni8yOTcyNTczNDUtZGMxNWQwODUtMDg4YS00ZjRkLWE1OGYtNmI4ZjRlYjVjMjhmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE3VDEzNDU1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZiMmM3NDAwNWJmZDJjYWJlYmUzMzAzMjBlMzM3Mzk4YWFjYjAyNDUxNDlhYzc3MzNiMjA1ODU2MmIwZDlhNmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wtqUlP_l2KhVQFyZzeZTi26lDrk2R6LqTB8oQFBNUVg">

done

2024-01-17 15:45 UTC, dreacot approved these changes

2024-01-17 15:45 UTC, merged