Handle locked coins properly
crypto-power/cryptopower pull request #403
Opened 2024-01-17 03:47 UTC by ukane-philemon

As requested by @itswisdomagain.
 
- Prevent dcr wallets from returning locked unspent utoxs in `wallet.UnspentOutputs`
- Display the correct locked, immature and spendable amounts on the wallet account page

UI

<img width="664" alt="Screenshot 2024-01-17 at 4 33 04 AM" src="https://github.com/crypto-power/cryptopower/assets/57448127/46a5de47-4df4-458c-9955-03dfcf6d6a7d">

<img width="620" alt="Screenshot 2024-01-17 at 4 32 44 AM" src="https://github.com/crypto-power/cryptopower/assets/57448127/17904d3a-91a2-4850-868c-fd59243ae59b">

2024-01-17 04:16 UTC, dreacot commented
i think you should add those balances to the account details page too

<img width="579" alt="Screenshot 2024-01-17 at 5 15 53 AM" src="https://github.com/crypto-power/cryptopower/assets/25265396/3d44de0a-7f29-41e7-a7c7-c24a1fbf3a69">

2024-01-17 04:22 UTC, dreacot commented
the pr says this only applies for dcr wallets? i see btc wallets are affected though, just confirming

2024-01-17 04:36 UTC, ukane-philemon commented
> the pr says this only applies for dcr wallets?

Part of.

2024-01-17 04:38 UTC, ukane-philemon commented
> i think you should add those balances to the account details page too

This will affect all other wallet pages too, yh?

2024-01-17 04:40 UTC, dreacot commented
> > the pr says this only applies for dcr wallets?
> 
> Part of.

i don't follow

2024-01-17 04:41 UTC, dreacot commented
> > i think you should add those balances to the account details page too
> 
> This will affect all other wallet pages too, yh?

how do you mean other wallet pages?

2024-01-17 04:45 UTC, ukane-philemon commented
> > > i think you should add those balances to the account details page too
> > 
> > 
> > This will affect all other wallet pages too, yh?
> 
> how do you mean other wallet pages?

Yes. Only dcr has more balances displayed on the details page.

2024-01-17 04:47 UTC, ukane-philemon commented
> > > the pr says this only applies for dcr wallets?
> > 
> > 
> > Part of.
> 
> i don't follow

I listed the issues fixed in the op comment.

2024-01-17 04:49 UTC, dreacot commented
> > > > i think you should add those balances to the account details page too
> > > 
> > > 
> > > This will affect all other wallet pages too, yh?
> > 
> > 
> > how do you mean other wallet pages?
> 
> Yes. Only dcr has more balances displayed on the details page.

okay, yeah then btc and ltc wallets shouldn't be showing locked and immature then

2024-01-17 04:53 UTC, ukane-philemon commented
> yeah then btc and ltc wallets shouldn't be showing locked and immature then

On the account page or details page or both? If users place trades on DEX, they'll need to know how much of their coins is locked by their wallet.

2024-01-17 04:58 UTC, dreacot commented
> > yeah then btc and ltc wallets shouldn't be showing locked and immature then
> 
> On the account page or details page or both? If users place trades on DEX, they'll need to know how much of their coins is locked by their wallet.

both

>If users place trades on DEX, they'll need to know how much of their coins is locked by their wallet.

then we can show locked for btc and ltc, but i don't know about immature, any of those changes on the account list page should be effected on the account details page though

2024-01-17 05:00 UTC, ukane-philemon commented
> but i don't know about immature

So I should remove this for btc and ltc only?

2024-01-17 05:06 UTC, dreacot commented
> > but i don't know about immature
> 
> So I should remove this for btc and ltc only?

yes, except we have use for them i am missing

2024-01-17 15:49 UTC, dreacot requested changes
i still don't see the other balances on my account details page

<img width="802" alt="Screenshot 2024-01-17 at 4 49 08 PM" src="https://github.com/crypto-power/cryptopower/assets/25265396/c97bdab7-c359-4d2a-a708-c737ebc56737">

2024-01-17 16:26 UTC, ukane-philemon commented
> i still don't see the other balances on my account details page
> 
> <img alt="Screenshot 2024-01-17 at 4 49 08 PM" width="802" src="https://private-user-images.githubusercontent.com/25265396/297436205-c97bdab7-c359-4d2a-a708-c737ebc56737.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU1MDkwMDIsIm5iZiI6MTcwNTUwODcwMiwicGF0aCI6Ii8yNTI2NTM5Ni8yOTc0MzYyMDUtYzk3YmRhYjctYzM1OS00ZDJhLWE3MDgtYzczN2ViYzU2NzM3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE3VDE2MjUwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEyMjYwNWU2Yjc4ZTc3YmExNzY5ZTgyMGNiMDcwZWVjYWFiNzFlNDljOTZmNzY1OGE2MTM3ZWZmMDUyODQ1ZGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0MxRqkSrdFzWOCaExkNvBm9-RETJvoE1KjsmZZOtjPU">

There are hidden on the details page if there’s no bal. You want them all to show always? Even when zero?

2024-01-17 16:33 UTC, dreacot commented
> > i still don't see the other balances on my account details page
> > <img alt="Screenshot 2024-01-17 at 4 49 08 PM" width="802" src="https://private-user-images.githubusercontent.com/25265396/297436205-c97bdab7-c359-4d2a-a708-c737ebc56737.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU1MDkwMDIsIm5iZiI6MTcwNTUwODcwMiwicGF0aCI6Ii8yNTI2NTM5Ni8yOTc0MzYyMDUtYzk3YmRhYjctYzM1OS00ZDJhLWE3MDgtYzczN2ViYzU2NzM3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE3VDE2MjUwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEyMjYwNWU2Yjc4ZTc3YmExNzY5ZTgyMGNiMDcwZWVjYWFiNzFlNDljOTZmNzY1OGE2MTM3ZWZmMDUyODQ1ZGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0MxRqkSrdFzWOCaExkNvBm9-RETJvoE1KjsmZZOtjPU">
> 
> They are hidden on the details page if there’s no bal. You want them all to show always? Even when zero? This behavior is only on the details page though.

yeah, if they show on the list page without balance, then they should show on the details page too, less confusing that way

2024-01-17 23:53 UTC, ukane-philemon commented
> yeah, if they show on the list page without balance, then they should show on the details page too, less confusing that way

Done in https://github.com/crypto-power/cryptopower/pull/403/commits/9bb6e975b8b470fd328cd17f71c1dfc9b1da3d10

2024-01-18 01:00 UTC, dreacot approved these changes

2024-01-18 01:00 UTC, merged