check latest released version from Github
crypto-power/cryptopower pull request #443
Opened 2024-01-31 16:15 UTC by dreacot

closes #91

2024-02-01 14:03 UTC, ukane-philemon requested changes

2024-02-01 14:05 UTC, ukane-philemon commented
Also, I think the desc text on the modal needs some bottom margin.

2024-02-07 13:10 UTC, dreacot commented on ui/values/strings.go
on master there's a gap here https://github.com/crypto-power/cryptopower/blob/master/ui/values/strings.go#L1041, so closing that gap seems to have confused git, into showing a huge diff

2024-02-07 14:23 UTC, ukane-philemon commented on ui/values/strings.go
Yh,  I see now. I had intentionally added the line space to separate the long text to prevent the huge diff in a previous PR.

2024-02-07 19:32 UTC, dreacot commented on ui/values/strings.go
Yeah, but we don’t need the gap to prevent the diff.

2024-02-07 19:40 UTC, ukane-philemon commented on ui/values/strings.go
Ok.

2024-02-07 19:40 UTC, ukane-philemon approved these changes

2024-02-07 20:17 UTC, merged