fix crash when pasting an empty text into the editor
crypto-power/cryptopower pull request #446
Opened 2024-02-01 11:58 UTC by dreacot

closes #445

2024-03-11 08:38 UTC, JustinBeBoy requested changes
Great work!

I think watch only wallet sync card should have another Icon for it
![image](https://github.com/crypto-power/cryptopower/assets/19331824/9c3b3bb4-c1eb-444b-9b89-928cc56a3924)

2024-03-11 08:44 UTC, JustinBeBoy commented
> fix watch only wallet balance not being accounted for

Why we need it? May be watch only wallet is not of them. Additional, if you want to add watch only wallet balance, it should is option and can setup on app setting

2024-03-15 18:48 UTC, dreacot commented
> Why we need it?

users are asking for it.

> can setup on app setting

we can do this in a different pr, or if users request for it

2024-03-16 09:29 UTC, JustinBeBoy approved these changes

2024-03-16 09:30 UTC, merged