fetch exchange rate api should pick a working default
crypto-power/cryptopower pull request #564
Opened 2024-07-04 08:19 UTC by vibros68

Closes #551 

* Fetch exchange rate option just fetchs the choosen exchange by user and up to 3 times for fetching rate. If all times is failed. So `none` option is choosen
* This mr add change by fetch all other available exchange which is supported
* This mr also remove support for bittrex since bittrex is no longer serving

2024-07-06 09:28 UTC, dreacot commented
```
2024-07-06 10:24:47.341 [ERR] EXT: fetching ticker 3 failed: binance failed to fetch ticker for LTC-USDT: Get "https://api.binance.com/api/v3/ticker/24hr?symbol=LTCUSDT": dial tcp: lookup api.binance.com: no such host. Retrying in 4s
2024-07-06 10:24:51.342 [INF] EXT: fetching from other exchanges
2024-07-06 10:24:52.498 [INF] EXT: messari is choosen
2024-07-06 10:24:52.500 [ERR] EXT: fetching ticker 1 failed: messari failed to fetch ticker for BTC-USDT: Get "https://api.binance.com/api/v3/ticker/24hr?symbol=BTCUSDT": dial tcp: lookup api.binance.com: no such host. Retrying in 1s
2024-07-06 10:24:53.502 [ERR] EXT: fetching ticker 2 failed: messari failed to fetch ticker for BTC-USDT: Get "https://api.binance.com/api/v3/ticker/24hr?symbol=BTCUSDT": dial tcp: lookup api.binance.com: no such host. Retrying in 2s
2024-07-06 10:24:55.507 [ERR] EXT: fetching ticker 3 failed: messari failed to fetch ticker for BTC-USDT: Get "https://api.binance.com/api/v3/ticker/24hr?symbol=BTCUSDT": dial tcp: lookup api.binance.com: no such host. Retrying in 4s
2024-07-06 10:24:59.508 [INF] EXT: fetching from other exchanges
2024-07-06 10:25:00.324 [INF] EXT: coinpaprika is choosen
2024-07-06 10:25:00.326 [ERR] EXT: fetching ticker 1 failed: coinpaprika failed to fetch ticker for DCR-USDT: Get "https://api.binance.com/api/v3/ticker/24hr?symbol=DCRUSDT": dial tcp: lookup api.binance.com: no such host. Retrying in 1s
2024-07-06 10:25:01.330 [ERR] EXT: fetching ticker 2 failed: coinpaprika failed to fetch ticker for DCR-USDT: Get "https://api.binance.com/api/v3/ticker/24hr?symbol=DCRUSDT": dial tcp: lookup api.binance.com: no such host. Retrying in 2s
2024-07-06 10:25:03.334 [ERR] EXT: fetching ticker 3 failed: coinpaprika failed to fetch ticker for DCR-USDT: Get "https://api.binance.com/api/v3/ticker/24hr?symbol=DCRUSDT": dial tcp: lookup api.binance.com: no such host. Retrying in 4s
2024-07-06 10:25:07.335 [INF] EXT: fetching from other exchanges
2024-07-06 10:25:07.619 [INF] EXT: messari is choosen
```

even though it says messari is chosen initially, it seems more api calls are still being made to try and determine a suitable default, and even after choosing messari, the UI still shows binance

<img width="545" alt="Screenshot 2024-07-06 at 10 27 12 AM" src="https://github.com/crypto-power/cryptopower/assets/25265396/6f0fa00d-78bb-400f-b13c-2dcaab09e929">

and if one fails, i don't think there is any need to try it 3 times anymore, just move on to checking the next available api

2024-07-06 09:29 UTC, vibros68 commented
Okay

2024-07-08 11:04 UTC, dreacot approved these changes

2024-07-08 11:04 UTC, dreacot commented on libwallet/ext/rate_source.go
> +				log.Infof("%s is choosen", source)
```suggestion
				log.Infof("%s is chosen", source)
```

2024-07-08 11:09 UTC, dreacot commented
please  with master, master contains dcrd v2.0 which has an upgraded database, so most devs are unable to test this PR

2024-07-08 12:27 UTC, dmigwi requested changes

2024-07-08 12:27 UTC, dmigwi commented on libwallet/ext/rate_source.go
> +	log.Infof("fetching %s rate from %v", market, cs.source)
this line would be best suited to run just before: 
```
newTicker, err = cs.getTicker(market)
```

At line 362

2024-07-08 12:27 UTC, dmigwi commented on libwallet/ext/rate_source.go
> +		log.Infof("fetching %s rate from %v", market, source)
Same to this, move it to where the fetch is actually happening.

2024-07-09 07:34 UTC, vibros68 commented
Done @dmigwi

2024-07-09 10:59 UTC, dmigwi approved these changes
LGTM

2024-07-11 11:40 UTC, dreacot commented
@vibros68 please rebase with master https://github.com/crypto-power/cryptopower/pull/564#issuecomment-2213709051

2024-07-12 04:17 UTC, JustinBeBoy requested changes

2024-07-12 04:17 UTC, JustinBeBoy commented on libwallet/ext/rate_source.go
> +	otherTickers  []tickerFunc
Remove otherTickers, I don't see anywhere use it

2024-07-12 04:19 UTC, JustinBeBoy commented
@vibros68 please clean code and we can merge

2024-07-12 06:16 UTC, vibros68 commented
@JustinBeBoy done

2024-07-12 06:37 UTC, JustinBeBoy approved these changes

2024-07-12 06:37 UTC, merged