Fix bug on send page
crypto-power/cryptopower pull request #602
Opened 2024-07-25 10:57 UTC by JustinBeBoy

Close #592

2024-07-29 21:01 UTC, dreacot commented
I have a wallet with just one account, that is the sending wallet, and i had selected the one account as the source account

i chose the wallets tab and selected same wallet, but there's no account to selected, which makes the destination account dropdown empty (happens on master too).

let's patch that here

<img width="830" alt="Screenshot 2024-07-29 at 9 57 54 PM" src="https://github.com/user-attachments/assets/d3aa5516-4147-4d4b-8cdc-b0b063d5e6ca">

2024-07-30 05:08 UTC, JustinBeBoy commented
> I have a wallet with just one account, that is the sending wallet, and i had selected the one account as the source account
> 
> i chose the wallets tab and selected same wallet, but there's no account to selected, which makes the destination account dropdown empty (happens on master too).
> 
> let's patch that here
> 
> <img alt="Screenshot 2024-07-29 at 9 57 54 PM" width="830" src="https://private-user-images.githubusercontent.com/25265396/353234328-d3aa5516-4147-4d4b-8cdc-b0b063d5e6ca.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIzMTU3NzAsIm5iZiI6MTcyMjMxNTQ3MCwicGF0aCI6Ii8yNTI2NTM5Ni8zNTMyMzQzMjgtZDNhYTU1MTYtNDE0Ny00ZDRiLThjZGMtYjBiMDYzZDVlNmNhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzMwVDA0NTc1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJhNjgyMmU3ZGZiZWE5ZGE3MDNmYWY1ZGM3MjU4YTg5ZDdmNGFhNjdkMGJmODJlODU3ZWQ0NjljMzJkMmU5NWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.cPqPuNaN2ISiVWOsFHADNbVp45KTe-tgHPG8SNs_w00">

So, what should we do?
I think may be we only show wallet tab when application have more than one wallet or one wallet with 2 accounts

2024-07-31 08:38 UTC, JustinBeBoy commented
> I have a wallet with just one account, that is the sending wallet, and i had selected the one account as the source account
> 
> i chose the wallets tab and selected same wallet, but there's no account to selected, which makes the destination account dropdown empty (happens on master too).
> 
> let's patch that here
> 
> <img alt="Screenshot 2024-07-29 at 9 57 54 PM" width="830" src="https://private-user-images.githubusercontent.com/25265396/353234328-d3aa5516-4147-4d4b-8cdc-b0b063d5e6ca.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI0MTU0MDAsIm5iZiI6MTcyMjQxNTEwMCwicGF0aCI6Ii8yNTI2NTM5Ni8zNTMyMzQzMjgtZDNhYTU1MTYtNDE0Ny00ZDRiLThjZGMtYjBiMDYzZDVlNmNhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzMxVDA4MzgyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM0YmE5MmY4NWUxOTVmOGViMGE4OWZhYzFhN2I5ZTM4MTNkNzYwNTM2ZGVmMmE1NGY0N2ZhNDg1NDE0OGU5MzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1bgmpBStBcVyH_x-BxgbisX8UI-pEOajLaU2vsIwwlw">

move to #606

2024-07-31 09:31 UTC, dreacot requested changes

2024-07-31 09:31 UTC, dreacot commented on libwallet/assets/btc/rescan.go
> -func (asset *Asset) rescanAsync() error {
why was this file deleted?

2024-07-31 09:31 UTC, dreacot commented on ui/cryptomaterial/editor.go
> +	isFocusShowHit bool
```suggestion
	showHintOnFocus bool
```

2024-07-31 09:31 UTC, dreacot commented on ui/cryptomaterial/editor.go
> +func (e *Editor) AlwayShowHit() {
```suggestion
func (e *Editor) AlwaysShowHint() {
```

2024-07-31 16:21 UTC, JustinBeBoy commented on libwallet/assets/btc/rescan.go
> -func (asset *Asset) rescanAsync() error {
it not use anywhere so i clean it

2024-08-01 11:23 UTC, dreacot approved these changes

2024-08-01 11:24 UTC, merged