Hide progress bar when mixer is not running
crypto-power/cryptopower pull request #70
Opened 2023-09-16 06:14 UTC by Vanvians

Closes #51.
Hides mixer status bar when the mixer is not activated
![remove mixer bar](https://github.com/crypto-power/cryptopower/assets/54014025/959e9541-3bfa-440d-9804-d519eeb10c49)

2023-09-16 06:38 UTC, Vanvians commented
Padding added to give cleaner look 
![Screenshot 2023-09-16 003523](https://github.com/crypto-power/cryptopower/assets/54014025/fc2c339c-c8c6-4f11-a908-36dd98ab6af6)

2023-09-22 14:04 UTC, dreacot approved these changes

2023-09-22 14:11 UTC, dreacot requested changes

2023-09-22 14:11 UTC, dreacot commented on ui/page/privacy/account_mixer_page.go
> +				if !pg.toggleMixer.IsChecked() {
```suggestion
				if !pg.dcrImpl.IsAccountMixerActive() {
```

2023-09-24 19:58 UTC, dreacot approved these changes

2023-09-24 19:58 UTC, merged